### PR TITLE
Avoid shadowing the global prompt function

### PR DESCRIPTION
**Pull request by rschroll**
The prompt variable inside issueAjaxRequest shadowed the prompt function
that it was attempting to use, thereby breaking the use of kt-prompt.

### CODE REVIEW

**Comment by chg20** [comment]
Hard one to test, thanks for catching that!

Can you retarget the 'dev' branch?

**Comment by rschroll** [comment]
Retargeted.

Yeah, I only caught this through trying things interactively.  I'm thinking adding it as an example would at least help manual testing.  Would you like that in this PR or in another one?

**Comment by chg20** [comment]
An example is a good idea. Maybe an example with both the query and prompt in it?

Cheers,
Carson

**Comment by chg20** [comment]
I ended up adding some manual tests for this.

Cheers,
Carson

**Pull request merged**
